import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_component/header";
import Footer from "./_component/footer";
import { ClerkProvider,  
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton, } from "@clerk/nextjs";


const roboto = Roboto({
  weight: "700",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

    <html lang="en" suppressHydrationWarning>
      <body
       className={roboto.className}
        suppressHydrationWarning
      >
        <Header/>
     
            <SignedIn>
              <UserButton />
            </SignedIn> 
        {children}
        <Footer/>
      </body>
    </html>
    </ClerkProvider>

  );
}
